url: "http://dejangrujic.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Dejan Grujic" # the name of your site, e.g. ACME Corp.

tagline: "Dejan Grujic radio voditelj, glumac i pisac."
email: dgrujic@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dejan Grujic je radio voditelj, glumac i pisac.
author: Dejan Grujic
google_analytics: G-YVGY1HEXS0
twitter:
  username: voditelj202
  card: summary #keep this to generate a twitter share card

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap