url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "dejangrujic" # the subpath of your site, e.g. /blog
title: "Dejan Grujic" # the name of your site, e.g. ACME Corp.
